# Generated by Django 4.0.5 on 2022-11-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.TextField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=150)),
                ('state', models.IntegerField()),
                ('zipcode', models.IntegerField()),
                ('available', models.BooleanField()),
            ],
        ),
    ]
