# Generated by Django 4.0.5 on 2022-11-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_profile_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(max_length=150),
        ),
    ]
