# Generated by Django 4.0.5 on 2022-11-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_profile_crud', '0002_alter_profile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank='', default='', upload_to='Images/'),
        ),
    ]
