# Generated by Django 4.0.5 on 2022-11-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_profile_crud', '0003_alter_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='img',
        ),
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.IntegerField(max_length=30),
        ),
    ]
