# Generated by Django 4.0.5 on 2022-11-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_profile_crud', '0005_alter_profile_zipcode_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank='', default='', upload_to='Images/'),
        ),
    ]
